package app.ehrenamtskarte.backend.exception.webservice.schema

enum class GraphQLExceptionCode {
    EMAIL_ALREADY_EXISTS,
    INVALID_LINK,
    INVALID_CREDENTIALS,
    INVALID_CODE_TYPE,
    INVALID_DATE_FORMAT,
    INVALID_FILE_TYPE,
    INVALID_FILE_SIZE,
    INVALID_JSON,
    INVALID_PASSWORD,
    INVALID_PASSWORD_RESET_LINK,
    INVALID_ROLE,
    MAIL_NOT_SENT,
    PASSWORD_RESET_KEY_EXPIRED,
    REGION_NOT_FOUND,
    WRONG_PASSWORD_EXCEPTION
}
