package app.ehrenamtskarte.backend.exception.webservice.schema

enum class GraphQLExceptionCode {
    USER_NOT_FOUND,
    EMPTY_INPUT,
    EMAIL_ALREADY_EXISTS,
    TOO_LONG_INPUT,
    INVALID_LINK,
    INVALID_CREDENTIALS,
    INVALID_CODE_TYPE,
    INVALID_DATE_FORMAT,
    INVALID_FILE_TYPE,
    INVALID_FILE_SIZE,
    INVALID_PASSWORD,
    INVALID_ROLE,
    TOO_YOUNG,
    MAIL_NOT_SENT,
    MISSING_AUTHORIZATION,
    PASSWORD_RESET_KEY_EXPIRED,
    REGION_NOT_FOUND,
    WRONG_PASSWORD_EXCEPTION
}
