package xyz.elitese.ehrenamtskarte;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: card_activate_model.proto

public final class CardActivateModelOuterClass {
  private CardActivateModelOuterClass() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardActivateModelOrBuilder extends
          // @@protoc_insertion_point(interface_extends:CardActivateModel)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fullName = 1;</code>
     * @return Whether the fullName field is set.
     */
    boolean hasFullName();
    /**
     * <code>required string fullName = 1;</code>
     * @return The fullName.
     */
    java.lang.String getFullName();
    /**
     * <code>required string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    com.google.protobuf.ByteString
    getFullNameBytes();

    /**
     * <code>optional string randomString = 2;</code>
     * @return Whether the randomString field is set.
     */
    boolean hasRandomString();
    /**
     * <code>optional string randomString = 2;</code>
     * @return The randomString.
     */
    java.lang.String getRandomString();
    /**
     * <code>optional string randomString = 2;</code>
     * @return The bytes for randomString.
     */
    com.google.protobuf.ByteString
    getRandomStringBytes();

    /**
     * <code>optional uint64 expirationDate = 3;</code>
     * @return Whether the expirationDate field is set.
     */
    boolean hasExpirationDate();
    /**
     * <code>optional uint64 expirationDate = 3;</code>
     * @return The expirationDate.
     */
    long getExpirationDate();

    /**
     * <code>required bytes totpSecret = 4;</code>
     * @return Whether the totpSecret field is set.
     */
    boolean hasTotpSecret();
    /**
     * <code>required bytes totpSecret = 4;</code>
     * @return The totpSecret.
     */
    com.google.protobuf.ByteString getTotpSecret();

    /**
     * <code>optional string cardType = 5;</code>
     * @return Whether the cardType field is set.
     */
    boolean hasCardType();
    /**
     * <code>optional string cardType = 5;</code>
     * @return The cardType.
     */
    java.lang.String getCardType();
    /**
     * <code>optional string cardType = 5;</code>
     * @return The bytes for cardType.
     */
    com.google.protobuf.ByteString
    getCardTypeBytes();

    /**
     * <code>optional int32 region = 6;</code>
     * @return Whether the region field is set.
     */
    boolean hasRegion();
    /**
     * <code>optional int32 region = 6;</code>
     * @return The region.
     */
    int getRegion();
  }
  /**
   * Protobuf type {@code CardActivateModel}
   */
  public static final class CardActivateModel extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:CardActivateModel)
          CardActivateModelOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use CardActivateModel.newBuilder() to construct.
    private CardActivateModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CardActivateModel() {
      fullName_ = "";
      randomString_ = "";
      totpSecret_ = com.google.protobuf.ByteString.EMPTY;
      cardType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new CardActivateModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CardActivateModel(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fullName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              randomString_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              expirationDate_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              totpSecret_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              cardType_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              region_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return CardActivateModelOuterClass.internal_static_CardActivateModel_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      CardActivateModelOuterClass.CardActivateModel.class, CardActivateModelOuterClass.CardActivateModel.Builder.class);
    }

    private int bitField0_;
    public static final int FULLNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fullName_;
    /**
     * <code>required string fullName = 1;</code>
     * @return Whether the fullName field is set.
     */
    @java.lang.Override
    public boolean hasFullName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string fullName = 1;</code>
     * @return The fullName.
     */
    @java.lang.Override
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANDOMSTRING_FIELD_NUMBER = 2;
    private volatile java.lang.Object randomString_;
    /**
     * <code>optional string randomString = 2;</code>
     * @return Whether the randomString field is set.
     */
    @java.lang.Override
    public boolean hasRandomString() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string randomString = 2;</code>
     * @return The randomString.
     */
    @java.lang.Override
    public java.lang.String getRandomString() {
      java.lang.Object ref = randomString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          randomString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string randomString = 2;</code>
     * @return The bytes for randomString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getRandomStringBytes() {
      java.lang.Object ref = randomString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        randomString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRATIONDATE_FIELD_NUMBER = 3;
    private long expirationDate_;
    /**
     * <code>optional uint64 expirationDate = 3;</code>
     * @return Whether the expirationDate field is set.
     */
    @java.lang.Override
    public boolean hasExpirationDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 expirationDate = 3;</code>
     * @return The expirationDate.
     */
    @java.lang.Override
    public long getExpirationDate() {
      return expirationDate_;
    }

    public static final int TOTPSECRET_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString totpSecret_;
    /**
     * <code>required bytes totpSecret = 4;</code>
     * @return Whether the totpSecret field is set.
     */
    @java.lang.Override
    public boolean hasTotpSecret() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required bytes totpSecret = 4;</code>
     * @return The totpSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTotpSecret() {
      return totpSecret_;
    }

    public static final int CARDTYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object cardType_;
    /**
     * <code>optional string cardType = 5;</code>
     * @return Whether the cardType field is set.
     */
    @java.lang.Override
    public boolean hasCardType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string cardType = 5;</code>
     * @return The cardType.
     */
    @java.lang.Override
    public java.lang.String getCardType() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cardType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cardType = 5;</code>
     * @return The bytes for cardType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getCardTypeBytes() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        cardType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGION_FIELD_NUMBER = 6;
    private int region_;
    /**
     * <code>optional int32 region = 6;</code>
     * @return Whether the region field is set.
     */
    @java.lang.Override
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 region = 6;</code>
     * @return The region.
     */
    @java.lang.Override
    public int getRegion() {
      return region_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFullName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotpSecret()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fullName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, randomString_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, expirationDate_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, totpSecret_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cardType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, region_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fullName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, randomString_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(3, expirationDate_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, totpSecret_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cardType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(6, region_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof CardActivateModelOuterClass.CardActivateModel)) {
        return super.equals(obj);
      }
      CardActivateModelOuterClass.CardActivateModel other = (CardActivateModelOuterClass.CardActivateModel) obj;

      if (hasFullName() != other.hasFullName()) return false;
      if (hasFullName()) {
        if (!getFullName()
                .equals(other.getFullName())) return false;
      }
      if (hasRandomString() != other.hasRandomString()) return false;
      if (hasRandomString()) {
        if (!getRandomString()
                .equals(other.getRandomString())) return false;
      }
      if (hasExpirationDate() != other.hasExpirationDate()) return false;
      if (hasExpirationDate()) {
        if (getExpirationDate()
                != other.getExpirationDate()) return false;
      }
      if (hasTotpSecret() != other.hasTotpSecret()) return false;
      if (hasTotpSecret()) {
        if (!getTotpSecret()
                .equals(other.getTotpSecret())) return false;
      }
      if (hasCardType() != other.hasCardType()) return false;
      if (hasCardType()) {
        if (!getCardType()
                .equals(other.getCardType())) return false;
      }
      if (hasRegion() != other.hasRegion()) return false;
      if (hasRegion()) {
        if (getRegion()
                != other.getRegion()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFullName()) {
        hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFullName().hashCode();
      }
      if (hasRandomString()) {
        hash = (37 * hash) + RANDOMSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getRandomString().hashCode();
      }
      if (hasExpirationDate()) {
        hash = (37 * hash) + EXPIRATIONDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getExpirationDate());
      }
      if (hasTotpSecret()) {
        hash = (37 * hash) + TOTPSECRET_FIELD_NUMBER;
        hash = (53 * hash) + getTotpSecret().hashCode();
      }
      if (hasCardType()) {
        hash = (37 * hash) + CARDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCardType().hashCode();
      }
      if (hasRegion()) {
        hash = (37 * hash) + REGION_FIELD_NUMBER;
        hash = (53 * hash) + getRegion();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CardActivateModelOuterClass.CardActivateModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CardActivateModel}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:CardActivateModel)
            CardActivateModelOuterClass.CardActivateModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        CardActivateModelOuterClass.CardActivateModel.class, CardActivateModelOuterClass.CardActivateModel.Builder.class);
      }

      // Construct using CardActivateModelOuterClass.CardActivateModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fullName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        randomString_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        expirationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        totpSecret_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        cardType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        region_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel getDefaultInstanceForType() {
        return CardActivateModelOuterClass.CardActivateModel.getDefaultInstance();
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel build() {
        CardActivateModelOuterClass.CardActivateModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel buildPartial() {
        CardActivateModelOuterClass.CardActivateModel result = new CardActivateModelOuterClass.CardActivateModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullName_ = fullName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.randomString_ = randomString_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.expirationDate_ = expirationDate_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totpSecret_ = totpSecret_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cardType_ = cardType_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.region_ = region_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CardActivateModelOuterClass.CardActivateModel) {
          return mergeFrom((CardActivateModelOuterClass.CardActivateModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CardActivateModelOuterClass.CardActivateModel other) {
        if (other == CardActivateModelOuterClass.CardActivateModel.getDefaultInstance()) return this;
        if (other.hasFullName()) {
          bitField0_ |= 0x00000001;
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.hasRandomString()) {
          bitField0_ |= 0x00000002;
          randomString_ = other.randomString_;
          onChanged();
        }
        if (other.hasExpirationDate()) {
          setExpirationDate(other.getExpirationDate());
        }
        if (other.hasTotpSecret()) {
          setTotpSecret(other.getTotpSecret());
        }
        if (other.hasCardType()) {
          bitField0_ |= 0x00000010;
          cardType_ = other.cardType_;
          onChanged();
        }
        if (other.hasRegion()) {
          setRegion(other.getRegion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFullName()) {
          return false;
        }
        if (!hasTotpSecret()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        CardActivateModelOuterClass.CardActivateModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CardActivateModelOuterClass.CardActivateModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fullName_ = "";
      /**
       * <code>required string fullName = 1;</code>
       * @return Whether the fullName field is set.
       */
      public boolean hasFullName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return The fullName.
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return The bytes for fullName.
       */
      public com.google.protobuf.ByteString
      getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fullName = 1;</code>
       * @param value The fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fullName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fullName = 1;</code>
       * @param value The bytes for fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        fullName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object randomString_ = "";
      /**
       * <code>optional string randomString = 2;</code>
       * @return Whether the randomString field is set.
       */
      public boolean hasRandomString() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string randomString = 2;</code>
       * @return The randomString.
       */
      public java.lang.String getRandomString() {
        java.lang.Object ref = randomString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            randomString_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string randomString = 2;</code>
       * @return The bytes for randomString.
       */
      public com.google.protobuf.ByteString
      getRandomStringBytes() {
        java.lang.Object ref = randomString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          randomString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string randomString = 2;</code>
       * @param value The randomString to set.
       * @return This builder for chaining.
       */
      public Builder setRandomString(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        randomString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string randomString = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRandomString() {
        bitField0_ = (bitField0_ & ~0x00000002);
        randomString_ = getDefaultInstance().getRandomString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string randomString = 2;</code>
       * @param value The bytes for randomString to set.
       * @return This builder for chaining.
       */
      public Builder setRandomStringBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        randomString_ = value;
        onChanged();
        return this;
      }

      private long expirationDate_ ;
      /**
       * <code>optional uint64 expirationDate = 3;</code>
       * @return Whether the expirationDate field is set.
       */
      @java.lang.Override
      public boolean hasExpirationDate() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 expirationDate = 3;</code>
       * @return The expirationDate.
       */
      @java.lang.Override
      public long getExpirationDate() {
        return expirationDate_;
      }
      /**
       * <code>optional uint64 expirationDate = 3;</code>
       * @param value The expirationDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpirationDate(long value) {
        bitField0_ |= 0x00000004;
        expirationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 expirationDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expirationDate_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString totpSecret_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes totpSecret = 4;</code>
       * @return Whether the totpSecret field is set.
       */
      @java.lang.Override
      public boolean hasTotpSecret() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required bytes totpSecret = 4;</code>
       * @return The totpSecret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTotpSecret() {
        return totpSecret_;
      }
      /**
       * <code>required bytes totpSecret = 4;</code>
       * @param value The totpSecret to set.
       * @return This builder for chaining.
       */
      public Builder setTotpSecret(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        totpSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes totpSecret = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotpSecret() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totpSecret_ = getDefaultInstance().getTotpSecret();
        onChanged();
        return this;
      }

      private java.lang.Object cardType_ = "";
      /**
       * <code>optional string cardType = 5;</code>
       * @return Whether the cardType field is set.
       */
      public boolean hasCardType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string cardType = 5;</code>
       * @return The cardType.
       */
      public java.lang.String getCardType() {
        java.lang.Object ref = cardType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cardType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cardType = 5;</code>
       * @return The bytes for cardType.
       */
      public com.google.protobuf.ByteString
      getCardTypeBytes() {
        java.lang.Object ref = cardType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          cardType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cardType = 5;</code>
       * @param value The cardType to set.
       * @return This builder for chaining.
       */
      public Builder setCardType(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        cardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cardType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cardType_ = getDefaultInstance().getCardType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cardType = 5;</code>
       * @param value The bytes for cardType to set.
       * @return This builder for chaining.
       */
      public Builder setCardTypeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        cardType_ = value;
        onChanged();
        return this;
      }

      private int region_ ;
      /**
       * <code>optional int32 region = 6;</code>
       * @return Whether the region field is set.
       */
      @java.lang.Override
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 region = 6;</code>
       * @return The region.
       */
      @java.lang.Override
      public int getRegion() {
        return region_;
      }
      /**
       * <code>optional int32 region = 6;</code>
       * @param value The region to set.
       * @return This builder for chaining.
       */
      public Builder setRegion(int value) {
        bitField0_ |= 0x00000020;
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 region = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        region_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CardActivateModel)
    }

    // @@protoc_insertion_point(class_scope:CardActivateModel)
    private static final CardActivateModelOuterClass.CardActivateModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CardActivateModelOuterClass.CardActivateModel();
    }

    public static CardActivateModelOuterClass.CardActivateModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CardActivateModel>
            PARSER = new com.google.protobuf.AbstractParser<CardActivateModel>() {
      @java.lang.Override
      public CardActivateModel parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new CardActivateModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CardActivateModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CardActivateModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CardActivateModelOuterClass.CardActivateModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_CardActivateModel_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_CardActivateModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\031card_activate_model.proto\"\211\001\n\021CardActi" +
                    "vateModel\022\020\n\010fullName\030\001 \002(\t\022\024\n\014randomStr" +
                    "ing\030\002 \001(\t\022\026\n\016expirationDate\030\003 \001(\004\022\022\n\ntot" +
                    "pSecret\030\004 \002(\014\022\020\n\010cardType\030\005 \001(\t\022\016\n\006regio" +
                    "n\030\006 \001(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_CardActivateModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_CardActivateModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_CardActivateModel_descriptor,
            new java.lang.String[] { "FullName", "RandomString", "ExpirationDate", "TotpSecret", "CardType", "Region", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
