package xyz.elitese.ehrenamtskarte;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: card_activate_model.proto

public final class CardActivateModelOuterClass {
  private CardActivateModelOuterClass() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardActivateModelOrBuilder extends
          // @@protoc_insertion_point(interface_extends:CardActivateModel)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fullName = 1;</code>
     * @return The fullName.
     */
    java.lang.String getFullName();
    /**
     * <code>string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    com.google.protobuf.ByteString
    getFullNameBytes();

    /**
     * <code>bytes randomBytes = 2;</code>
     * @return The randomBytes.
     */
    com.google.protobuf.ByteString getRandomBytes();

    /**
     * <code>uint64 expirationDate = 3;</code>
     * @return The expirationDate.
     */
    long getExpirationDate();

    /**
     * <code>bytes totpSecret = 4;</code>
     * @return The totpSecret.
     */
    com.google.protobuf.ByteString getTotpSecret();

    /**
     * <code>.CardActivateModel.CardType cardType = 5;</code>
     * @return The enum numeric value on the wire for cardType.
     */
    int getCardTypeValue();
    /**
     * <code>.CardActivateModel.CardType cardType = 5;</code>
     * @return The cardType.
     */
    CardActivateModelOuterClass.CardActivateModel.CardType getCardType();

    /**
     * <code>int32 region = 6;</code>
     * @return The region.
     */
    int getRegion();
  }
  /**
   * Protobuf type {@code CardActivateModel}
   */
  public static final class CardActivateModel extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:CardActivateModel)
          CardActivateModelOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use CardActivateModel.newBuilder() to construct.
    private CardActivateModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CardActivateModel() {
      fullName_ = "";
      randomBytes_ = com.google.protobuf.ByteString.EMPTY;
      totpSecret_ = com.google.protobuf.ByteString.EMPTY;
      cardType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new CardActivateModel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CardActivateModel(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fullName_ = s;
              break;
            }
            case 18: {

              randomBytes_ = input.readBytes();
              break;
            }
            case 24: {

              expirationDate_ = input.readUInt64();
              break;
            }
            case 34: {

              totpSecret_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              cardType_ = rawValue;
              break;
            }
            case 48: {

              region_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return CardActivateModelOuterClass.internal_static_CardActivateModel_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      CardActivateModelOuterClass.CardActivateModel.class, CardActivateModelOuterClass.CardActivateModel.Builder.class);
    }

    /**
     * Protobuf enum {@code CardActivateModel.CardType}
     */
    public enum CardType
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STANDARD = 0;</code>
       */
      STANDARD(0),
      /**
       * <code>GOLD = 1;</code>
       */
      GOLD(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>STANDARD = 0;</code>
       */
      public static final int STANDARD_VALUE = 0;
      /**
       * <code>GOLD = 1;</code>
       */
      public static final int GOLD_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
                  "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CardType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CardType forNumber(int value) {
        switch (value) {
          case 0: return STANDARD;
          case 1: return GOLD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CardType>
      internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
              CardType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<CardType>() {
                public CardType findValueByNumber(int number) {
                  return CardType.forNumber(number);
                }
              };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
                  "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return CardActivateModelOuterClass.CardActivateModel.getDescriptor().getEnumTypes().get(0);
      }

      private static final CardType[] VALUES = values();

      public static CardType valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CardType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CardActivateModel.CardType)
    }

    public static final int FULLNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fullName_;
    /**
     * <code>string fullName = 1;</code>
     * @return The fullName.
     */
    @java.lang.Override
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      }
    }
    /**
     * <code>string fullName = 1;</code>
     * @return The bytes for fullName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANDOMBYTES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString randomBytes_;
    /**
     * <code>bytes randomBytes = 2;</code>
     * @return The randomBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRandomBytes() {
      return randomBytes_;
    }

    public static final int EXPIRATIONDATE_FIELD_NUMBER = 3;
    private long expirationDate_;
    /**
     * <code>uint64 expirationDate = 3;</code>
     * @return The expirationDate.
     */
    @java.lang.Override
    public long getExpirationDate() {
      return expirationDate_;
    }

    public static final int TOTPSECRET_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString totpSecret_;
    /**
     * <code>bytes totpSecret = 4;</code>
     * @return The totpSecret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTotpSecret() {
      return totpSecret_;
    }

    public static final int CARDTYPE_FIELD_NUMBER = 5;
    private int cardType_;
    /**
     * <code>.CardActivateModel.CardType cardType = 5;</code>
     * @return The enum numeric value on the wire for cardType.
     */
    @java.lang.Override public int getCardTypeValue() {
      return cardType_;
    }
    /**
     * <code>.CardActivateModel.CardType cardType = 5;</code>
     * @return The cardType.
     */
    @java.lang.Override public CardActivateModelOuterClass.CardActivateModel.CardType getCardType() {
      @SuppressWarnings("deprecation")
      CardActivateModelOuterClass.CardActivateModel.CardType result = CardActivateModelOuterClass.CardActivateModel.CardType.valueOf(cardType_);
      return result == null ? CardActivateModelOuterClass.CardActivateModel.CardType.UNRECOGNIZED : result;
    }

    public static final int REGION_FIELD_NUMBER = 6;
    private int region_;
    /**
     * <code>int32 region = 6;</code>
     * @return The region.
     */
    @java.lang.Override
    public int getRegion() {
      return region_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getFullNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fullName_);
      }
      if (!randomBytes_.isEmpty()) {
        output.writeBytes(2, randomBytes_);
      }
      if (expirationDate_ != 0L) {
        output.writeUInt64(3, expirationDate_);
      }
      if (!totpSecret_.isEmpty()) {
        output.writeBytes(4, totpSecret_);
      }
      if (cardType_ != CardActivateModelOuterClass.CardActivateModel.CardType.STANDARD.getNumber()) {
        output.writeEnum(5, cardType_);
      }
      if (region_ != 0) {
        output.writeInt32(6, region_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFullNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fullName_);
      }
      if (!randomBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, randomBytes_);
      }
      if (expirationDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt64Size(3, expirationDate_);
      }
      if (!totpSecret_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, totpSecret_);
      }
      if (cardType_ != CardActivateModelOuterClass.CardActivateModel.CardType.STANDARD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(5, cardType_);
      }
      if (region_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(6, region_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof CardActivateModelOuterClass.CardActivateModel)) {
        return super.equals(obj);
      }
      CardActivateModelOuterClass.CardActivateModel other = (CardActivateModelOuterClass.CardActivateModel) obj;

      if (!getFullName()
              .equals(other.getFullName())) return false;
      if (!getRandomBytes()
              .equals(other.getRandomBytes())) return false;
      if (getExpirationDate()
              != other.getExpirationDate()) return false;
      if (!getTotpSecret()
              .equals(other.getTotpSecret())) return false;
      if (cardType_ != other.cardType_) return false;
      if (getRegion()
              != other.getRegion()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
      hash = (37 * hash) + RANDOMBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getRandomBytes().hashCode();
      hash = (37 * hash) + EXPIRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getExpirationDate());
      hash = (37 * hash) + TOTPSECRET_FIELD_NUMBER;
      hash = (53 * hash) + getTotpSecret().hashCode();
      hash = (37 * hash) + CARDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + cardType_;
      hash = (37 * hash) + REGION_FIELD_NUMBER;
      hash = (53 * hash) + getRegion();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static CardActivateModelOuterClass.CardActivateModel parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CardActivateModelOuterClass.CardActivateModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CardActivateModel}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:CardActivateModel)
            CardActivateModelOuterClass.CardActivateModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        CardActivateModelOuterClass.CardActivateModel.class, CardActivateModelOuterClass.CardActivateModel.Builder.class);
      }

      // Construct using CardActivateModelOuterClass.CardActivateModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fullName_ = "";

        randomBytes_ = com.google.protobuf.ByteString.EMPTY;

        expirationDate_ = 0L;

        totpSecret_ = com.google.protobuf.ByteString.EMPTY;

        cardType_ = 0;

        region_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return CardActivateModelOuterClass.internal_static_CardActivateModel_descriptor;
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel getDefaultInstanceForType() {
        return CardActivateModelOuterClass.CardActivateModel.getDefaultInstance();
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel build() {
        CardActivateModelOuterClass.CardActivateModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel buildPartial() {
        CardActivateModelOuterClass.CardActivateModel result = new CardActivateModelOuterClass.CardActivateModel(this);
        result.fullName_ = fullName_;
        result.randomBytes_ = randomBytes_;
        result.expirationDate_ = expirationDate_;
        result.totpSecret_ = totpSecret_;
        result.cardType_ = cardType_;
        result.region_ = region_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CardActivateModelOuterClass.CardActivateModel) {
          return mergeFrom((CardActivateModelOuterClass.CardActivateModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CardActivateModelOuterClass.CardActivateModel other) {
        if (other == CardActivateModelOuterClass.CardActivateModel.getDefaultInstance()) return this;
        if (!other.getFullName().isEmpty()) {
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.getRandomBytes() != com.google.protobuf.ByteString.EMPTY) {
          setRandomBytes(other.getRandomBytes());
        }
        if (other.getExpirationDate() != 0L) {
          setExpirationDate(other.getExpirationDate());
        }
        if (other.getTotpSecret() != com.google.protobuf.ByteString.EMPTY) {
          setTotpSecret(other.getTotpSecret());
        }
        if (other.cardType_ != 0) {
          setCardTypeValue(other.getCardTypeValue());
        }
        if (other.getRegion() != 0) {
          setRegion(other.getRegion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        CardActivateModelOuterClass.CardActivateModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CardActivateModelOuterClass.CardActivateModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fullName_ = "";
      /**
       * <code>string fullName = 1;</code>
       * @return The fullName.
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fullName = 1;</code>
       * @return The bytes for fullName.
       */
      public com.google.protobuf.ByteString
      getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fullName = 1;</code>
       * @param value The fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fullName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullName() {

        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>string fullName = 1;</code>
       * @param value The bytes for fullName to set.
       * @return This builder for chaining.
       */
      public Builder setFullNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        fullName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString randomBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes randomBytes = 2;</code>
       * @return The randomBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRandomBytes() {
        return randomBytes_;
      }
      /**
       * <code>bytes randomBytes = 2;</code>
       * @param value The randomBytes to set.
       * @return This builder for chaining.
       */
      public Builder setRandomBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        randomBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes randomBytes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRandomBytes() {

        randomBytes_ = getDefaultInstance().getRandomBytes();
        onChanged();
        return this;
      }

      private long expirationDate_ ;
      /**
       * <code>uint64 expirationDate = 3;</code>
       * @return The expirationDate.
       */
      @java.lang.Override
      public long getExpirationDate() {
        return expirationDate_;
      }
      /**
       * <code>uint64 expirationDate = 3;</code>
       * @param value The expirationDate to set.
       * @return This builder for chaining.
       */
      public Builder setExpirationDate(long value) {

        expirationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 expirationDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpirationDate() {

        expirationDate_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString totpSecret_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes totpSecret = 4;</code>
       * @return The totpSecret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTotpSecret() {
        return totpSecret_;
      }
      /**
       * <code>bytes totpSecret = 4;</code>
       * @param value The totpSecret to set.
       * @return This builder for chaining.
       */
      public Builder setTotpSecret(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        totpSecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes totpSecret = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotpSecret() {

        totpSecret_ = getDefaultInstance().getTotpSecret();
        onChanged();
        return this;
      }

      private int cardType_ = 0;
      /**
       * <code>.CardActivateModel.CardType cardType = 5;</code>
       * @return The enum numeric value on the wire for cardType.
       */
      @java.lang.Override public int getCardTypeValue() {
        return cardType_;
      }
      /**
       * <code>.CardActivateModel.CardType cardType = 5;</code>
       * @param value The enum numeric value on the wire for cardType to set.
       * @return This builder for chaining.
       */
      public Builder setCardTypeValue(int value) {

        cardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CardActivateModel.CardType cardType = 5;</code>
       * @return The cardType.
       */
      @java.lang.Override
      public CardActivateModelOuterClass.CardActivateModel.CardType getCardType() {
        @SuppressWarnings("deprecation")
        CardActivateModelOuterClass.CardActivateModel.CardType result = CardActivateModelOuterClass.CardActivateModel.CardType.valueOf(cardType_);
        return result == null ? CardActivateModelOuterClass.CardActivateModel.CardType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CardActivateModel.CardType cardType = 5;</code>
       * @param value The cardType to set.
       * @return This builder for chaining.
       */
      public Builder setCardType(CardActivateModelOuterClass.CardActivateModel.CardType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cardType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CardActivateModel.CardType cardType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardType() {

        cardType_ = 0;
        onChanged();
        return this;
      }

      private int region_ ;
      /**
       * <code>int32 region = 6;</code>
       * @return The region.
       */
      @java.lang.Override
      public int getRegion() {
        return region_;
      }
      /**
       * <code>int32 region = 6;</code>
       * @param value The region to set.
       * @return This builder for chaining.
       */
      public Builder setRegion(int value) {

        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 region = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegion() {

        region_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CardActivateModel)
    }

    // @@protoc_insertion_point(class_scope:CardActivateModel)
    private static final CardActivateModelOuterClass.CardActivateModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CardActivateModelOuterClass.CardActivateModel();
    }

    public static CardActivateModelOuterClass.CardActivateModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CardActivateModel>
            PARSER = new com.google.protobuf.AbstractParser<CardActivateModel>() {
      @java.lang.Override
      public CardActivateModel parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new CardActivateModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CardActivateModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CardActivateModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CardActivateModelOuterClass.CardActivateModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_CardActivateModel_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_CardActivateModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\031card_activate_model.proto\"\311\001\n\021CardActi" +
                    "vateModel\022\020\n\010fullName\030\001 \001(\t\022\023\n\013randomByt" +
                    "es\030\002 \001(\014\022\026\n\016expirationDate\030\003 \001(\004\022\022\n\ntotp" +
                    "Secret\030\004 \001(\014\022-\n\010cardType\030\005 \001(\0162\033.CardAct" +
                    "ivateModel.CardType\022\016\n\006region\030\006 \001(\005\"\"\n\010C" +
                    "ardType\022\014\n\010STANDARD\020\000\022\010\n\004GOLD\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_CardActivateModel_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_CardActivateModel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_CardActivateModel_descriptor,
            new java.lang.String[] { "FullName", "RandomBytes", "ExpirationDate", "TotpSecret", "CardType", "Region", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
