changelog:
  categories:
    - title: Features, fixes, enhancements 🎉
      labels:
        - '*'
      exclude:
        labels:
        - not-testable
        - Nuernberg
    - title: Testable features for nuernberg 🎉
      labels:
        - Nuernberg
    - title: Maintenance 🛠
      labels:
        - not-testable
