include: package:effective_dart/analysis_options.1.3.0.yaml

analyzer:
  exclude:
    - build/**
    - lib/graphql/*.graphql.dart
    - lib/graphql/*.graphql.g.dart
    - lib/identification/protobuf/*.dart
  errors:
    missing_required_param: warning

linter:
  rules:
    public_member_api_docs: false
