# Read about `build.yaml` at https://pub.dev/packages/build_config


targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - graphql_queries/**
      - schema.graphql
      - build-configs/**
    builders:
      df_build_config:
        generate_for:
          include: 
            - "build-configs/**/index.ts"
        enabled: True
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql_queries/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: Long
              dart_type: int
            - graphql_type: Upload
              custom_parser_import: 'upload_parser.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
