############
# FRONTEND #
############

fe_task_without_container_template: &FE_TASK_WITHOUT_CONTAINER_TEMPLATE
  container:
    image: cirrusci/flutter:latest
  pub_cache:
    folder: ~/.pub-cache
    reupload_on_changes: false # since there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS
      - flutter --version
      - cat frontend/pubspec.lock
    populate_script:
      - cd frontend
      - flutter pub get

fe_task_template: &FE_TASK_TEMPLATE
  << : *FE_TASK_WITHOUT_CONTAINER_TEMPLATE
  container:
    image: cirrusci/flutter:latest

fe_analyze_task:
  name: "FE: analyze"
  << : *FE_TASK_TEMPLATE
  analyze_script:
    - cd frontend
    - flutter analyze

fe_test_task:
  name: "FE: test"
  << : *FE_TASK_TEMPLATE
  test_script:
    - cd frontend
    - flutter test

fe_build_ios_task:
  name: "FE: build (iOS)"
  << : *FE_TASK_WITHOUT_CONTAINER_TEMPLATE
  required_pr_labels: build-ios
  depends_on:
    - "FE: analyze"
    - "FE: test"
  osx_instance:
      image: catalina-flutter
  build_script:
    - cd frontend
    - flutter build ios --release --no-codesign -t lib/main_prod.dart
  iOS_app_artifacts:
    path: ./frontend/build/ios/iphoneos/Runner.app

fe_build_android_task:
  name: "FE: build (Android)"
  << : *FE_TASK_TEMPLATE
  depends_on:
    - "FE: analyze"
    - "FE: test"
  build_script:
    - cd frontend
    - flutter build appbundle -t lib/main_prod.dart
  android_app_artifacts:
    path: ./frontend/build/app/outputs/bundle/release/app-release.aab
