# Important:
# - All updates in this file have to added/adjusted in salt before deployment!
# - Example: https://git.tuerantuer.org/DF/salt/src/branch/master/pillars/entitlementcard/production/bayern.sls
environment: development
postgres:
  url: jdbc:postgresql://localhost:5432/ehrenamtskarte
  user: postgres
  password: postgres
map:
  # baseUrl: https://tiles.entitlementcard.app/physical_stores/{z}/{x}/{y}
  baseUrl: http://localhost:5002/physical_stores/{z}/{x}/{y}
geocoding:
  enabled: false
  host: nominatim.maps.tuerantuer.org
server:
  host: 0.0.0.0
  port: 8000
  dataDirectory: ./data
matomoUrl: http://localhost:5003/matomo.php
projects:
  - id: bayern.ehrenamtskarte.app
    importUrl: https://www.ehrenamt.bayern.de/xml-json/app-daten.xml
    pipelineName: EhrenamtskarteBayern
    administrationBaseUrl: https://bayern.ehrenamtskarte.app
    administrationName: Ehrenamtskarte-Bayern-Verwaltung
    emailSignature: Ihr Team der Ehrenamtskarte Bayern
    timezone: "Europe/Berlin"
    selfServiceEnabled: false
    smtp:
      host: mail.ehrenamtskarte.app
      port: 587
      username: OVERRIDE_IN_LOCAL_CONFIG
      password: OVERRIDE_IN_LOCAL_CONFIG
    freinet:
      host: freinet-online.de
      path: /query/api/portal/v1/MandantenMatchingServiceEndpoint.php
      portalId: 102
      accessToken: OVERRIDE_IN_LOCAL_CONFIG
  - id: nuernberg.sozialpass.app
    importUrl: ""
    administrationBaseUrl: https://nuernberg.sozialpass.app
    administrationName: Nürnberg-Pass-Verwaltung
    emailSignature: Ihr Team des Nürnberg-Passes
    timezone: "Europe/Berlin"
    selfServiceEnabled: false
    smtp:
      host: mail.sozialpass.app
      port: 587
      username: OVERRIDE_IN_LOCAL_CONFIG
      password: OVERRIDE_IN_LOCAL_CONFIG
  - id: koblenz.sozialpass.app
    importUrl: ""
    administrationBaseUrl: https://koblenz.sozialpass.app
    administrationName: Koblenz-Pass-Verwaltung
    emailSignature: Ihr Team des KoblenzPasses
    timezone: "Europe/Berlin"
    selfServiceEnabled: true
    smtp:
      host: mail.sozialpass.app
      port: 587
      username: OVERRIDE_IN_LOCAL_CONFIG
      password: OVERRIDE_IN_LOCAL_CONFIG
  - id: showcase.entitlementcard.app
    importUrl: https://example.com
    administrationBaseUrl: https://showcase.entitlementcard.app
    administrationName: Showcase-Entitlementcard-Verwaltung
    emailSignature: Ihr Team der Ehrenamtskarte
    timezone: "Europe/Berlin"
    selfServiceEnabled: false
    smtp:
      host: mail.sozialpass.app
      port: 587
      username: OVERRIDE_IN_LOCAL_CONFIG
      password: OVERRIDE_IN_LOCAL_CONFIG
