when:
  or:
    - equal: [<< pipeline.parameters.run_commit_main >>, "run"]
    - and:
      - equal: [<< pipeline.parameters.run_commit_main >>, "run_if_on_main"]
      - equal: [main, << pipeline.git.branch >>]
jobs:
  - bump_version:
      prepare_delivery: false

  - build_administration:
      requires:
        - bump_version
  - build_backend:
      requires:
        - bump_version
  - build_android:
      build_config: bayern
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
      requires:
        - bump_version
  - build_ios:
      build_config: bayern
      requires:
        - bump_version
      context:
        - tuerantuer-apple
        - fastlane-match
