when:
  or:
    - equal: [<< pipeline.parameters.run_commit_main >>, "run"]
    - and:
      - equal: [<< pipeline.parameters.run_commit_main >>, "run_if_on_main"]
      - equal: [main, << pipeline.git.branch >>]
jobs:
  - bump_version:
        prepare_delivery: false
  - check_administration
  - check_backend
  - build_administration:
      requires:
        - check_administration
        - bump_version
  - pack_administration:
      requires:
        - build_administration
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - build_backend
        - bump_version
  - pack_martin:
      requires:
        - bump_version
  - pack_meta:
      requires:
        - bump_version
  - check_frontend
  - build_android:
      name: build_android_bayern
      buildConfig: "bayern"
      requires:
        - bump_version
        - check_frontend
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
  - build_ios:
      name: build_ios_bayern
      buildConfig: "bayern"
      requires:
        - bump_version
        - check_frontend
      context:
        - tuerantuer-apple
        - fastlane-match