when:
  and:
    - << pipeline.parameters.run_commit >>
    - not:
        equal: [ main, << pipeline.git.branch >> ]
jobs:
  - check_backend
# Commented out, because we test gh actions ./github/workflows/check-administration
#  - check_administration
  - check_frontend
