when:
  or:
    - equal: [<< pipeline.parameters.run_commit_main >>, "run"]
    - and:
      - equal: [<< pipeline.parameters.run_commit_main >>, "run_if_on_main"]
      - equal: [main, << pipeline.git.branch >>]
jobs:
  - bump_version:
      prepare_delivery: false
  - pack_martin:
      requires:
        - bump_version
  - pack_meta:
      requires:
        - bump_version

  - check_administration
  - build_administration:
      requires:
        - bump_version
        - check_administration
  - pack_administration:
      requires:
        - build_administration

  - check_backend
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - bump_version
        - build_backend

  - check_frontend
  - build_android:
      build_config: nuernberg
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
      requires:
        - bump_version
        - check_frontend
  - build_ios:
      build_config: nuernberg
      requires:
        - bump_version
        - check_frontend
      context:
        - tuerantuer-apple
        - fastlane-match
