# Please use the delivery_beta_backend_administration and promote_backend_administration workflows. This is just for emergencies.
when: << pipeline.parameters.run_delivery_production_backend_administration >>
jobs:
  - bump_version:
      prepare_delivery: true
      platforms: web
      context:
        - deliverino
  - pack_martin:
      requires:
        - bump_version
  - pack_meta:
      requires:
        - bump_version

  - check_administration
  - build_administration:
      requires:
        - bump_version
        - check_administration
  - pack_administration:
      requires:
        - build_administration

  - check_backend
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - bump_version
        - build_backend

  - deliver_server:
      production: true
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - pack_backend
        - pack_martin
        - pack_meta
  - notify_release:
      production_delivery: true
      context:
        - deliverino
      requires:
        - deliver_server

