# Please use the delivery_beta_backend_administration and promote_backend_administration workflows. This is just for emergencies.
when: << pipeline.parameters.run_delivery_production_backend_administration >>
jobs:
  - bump_version:
      prepare_delivery: true
      platforms: web
      context:
        - deliverino
  - check_administration
  - build_administration:
      requires:
        - check_administration
        - bump_version
  - pack_administration:
      requires:
        - build_administration
  - build_martin
  - check_backend
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - build_backend
        - bump_version
  - check_health_backend:
      requires:
        - pack_backend
  - pack_martin:
      requires:
        - build_martin
        - bump_version
  - pack_meta:
      requires:
        - bump_version
  - upload_packages_to_server:
      name: upload_administration_packages_to_server_production
      production: true
      bundle: administration
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - check_health_backend
        - pack_martin
        - pack_meta
  - upload_packages_to_server:
      name: upload_backend_packages_to_server_production
      production: true
      bundle: backend
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - check_health_backend
        - pack_martin
        - pack_meta
  - install_packages_to_server:
      name: install_packages_to_server_production
      production: true
      context:
        - credentials-ehrenamtskarte
      requires:
        - upload_administration_packages_to_server_production
        - upload_backend_packages_to_server_production
  - notify_release:
      production_delivery: true
      context:
        - deliverino
      requires:
        - install_packages_to_server_production

