when: << pipeline.parameters.run_delivery_production_frontend >>
jobs:
  - bump_version:
      prepare_delivery: true
      platforms: native
      context:
        - deliverino
  - check_frontend
  - build_android:
      name: build_android_bayern
      buildConfig: "bayern"
      requires:
        - bump_version
        - check_frontend
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
  - deliver_android:
      name: deliver_android_bayern
      buildConfig: "bayern"
      context:
        - tuerantuer-google-play
      production_delivery: true
      requires:
        - build_android_bayern
  - build_android:
      name: build_android_nuernberg
      buildConfig: "nuernberg"
      requires:
        - bump_version
        - check_frontend
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
  - deliver_android:
      name: deliver_android_nuernberg
      buildConfig: "nuernberg"
      context:
        - tuerantuer-google-play
      production_delivery: true
      requires:
        - build_android_nuernberg
#  - build_android:
#      name: build_android_koblenz
#      buildConfig: "koblenz"
#      requires:
#        - bump_version
#        - check_frontend
#      context:
#        - credentials-repo
#        - credentials-ehrenamtskarte
#  - deliver_android:
#      name: deliver_android_koblenz
#      buildConfig: "koblenz"
#      context:
#        - tuerantuer-google-play
#      production_delivery: true
#      requires:
#        - build_android_koblenz
  - build_ios:
      name: build_ios_bayern
      buildConfig: "bayern"
      requires:
        - bump_version
        - check_frontend
      context:
        - tuerantuer-apple
        - fastlane-match
  - deliver_ios:
      name: deliver_ios_bayern
      buildConfig: bayern
      context:
        - tuerantuer-apple
      production_delivery: true
      requires:
        - build_ios_bayern
  - build_ios:
      name: build_ios_nuernberg
      buildConfig: "nuernberg"
      requires:
        - bump_version
        - check_frontend
      context:
        - tuerantuer-apple
        - fastlane-match
  - deliver_ios:
      name: deliver_ios_nuernberg
      buildConfig: nuernberg
      context:
        - tuerantuer-apple
      production_delivery: true
      requires:
        - build_ios_nuernberg
#  - build_ios:
#      name: build_ios_koblenz
#      buildConfig: "koblenz"
#      requires:
#        - bump_version
#        - check_frontend
#      context:
#        - tuerantuer-apple
#        - fastlane-match
#  - deliver_ios:
#      name: deliver_ios_koblenz
#      buildConfig: koblenz
#      context:
#        - tuerantuer-apple
#      production_delivery: true
#      requires:
#        - build_ios_koblenz
  - notify_release:
      production_delivery: true
      context:
        - deliverino
      requires:
        - deliver_ios_bayern
        - deliver_ios_nuernberg
#        - deliver_ios_koblenz
        - deliver_android_bayern
        - deliver_android_nuernberg
#        - deliver_android_koblenz
