when: << pipeline.parameters.run_delivery_beta_all >>
jobs:
  - bump_version:
      prepare_delivery: true
      context:
        - deliverino

  - check_frontend
  - build_android:
      name: build_android_<< matrix.build_config >>
      matrix:
        parameters:
          build_config: [bayern, nuernberg, koblenz]
      context:
        - credentials-repo
        - credentials-ehrenamtskarte
      requires:
        - bump_version
        - check_frontend
  - deliver_android:
      production_delivery: false
      matrix:
        parameters:
          build_config: [bayern, nuernberg, koblenz]
      context:
        - tuerantuer-google-play
      requires:
        - build_android_<< matrix.build_config >>

  - build_ios:
      name: build_ios_<< matrix.build_config >>
      matrix:
        parameters:
          build_config: [bayern, nuernberg, koblenz]
      requires:
        - bump_version
        - check_frontend
      context:
        - tuerantuer-apple
        - fastlane-match
  - deliver_ios:
      production_delivery: false
      matrix:
        parameters:
          build_config: [bayern, nuernberg, koblenz]
      context:
        - tuerantuer-apple
      requires:
        - build_ios_<< matrix.build_config >>

  - pack_martin:
      requires:
        - bump_version
  - pack_meta:
      requires:
        - bump_version

  - check_administration
  - build_administration:
      requires:
        - check_administration
        - bump_version
  - pack_administration:
      requires:
        - build_administration

  - check_backend
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - build_backend
        - bump_version

  - deliver_server:
      production: false
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - pack_backend
        - pack_martin
        - pack_meta

  - notify_release:
      production_delivery: false
      context:
        - deliverino
      requires:
        - deliver_android
        - deliver_ios
        - deliver_server
