export { buildConfigNuernberg, NUERNBERG_PRODUCTION_ID, NUERNBERG_STAGING_ID } from './nuernberg'
export { buildConfigBayern, BAYERN_STAGING_ID, BAYERN_PRODUCTION_ID } from './bayern'
export { buildConfigKoblenz, KOBLENZ_STAGING_ID, KOBLENZ_PRODUCTION_ID } from './koblenz'
export type { DeeplLinkingConfig, BuildConfigType } from './types'
export * from './constants'
