INSERT INTO
    public.applications ("id", "regionId","jsonValue","createdDate","accessKey","withdrawalDate","note","status", "statusResolvedDate")
VALUES
	-- Verification approved
    (
     1, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-03-25 16:32:33.499253','access_key_01',NULL,NULL, 'Pending', null
    ),
    -- Verification rejected
    (
     2, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-03-25 16:32:33.499253','access_key_02',NULL,NULL, 'Pending', null
    ),
    -- Verification approved, withdrawn
    (
     3, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-03-25 16:32:33.499253','access_key_03',current_timestamp,NULL,'Pending', null
    ),
    -- Verification rejected, withdrawn
    (
     4, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
    '2025-03-25 16:32:33.499253','access_key_04',current_timestamp,NULL,'Pending', null
    ),
    -- Verification undecided verification
    (
     5, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-03-25 16:32:33.499253','access_key_05',NULL,NULL,'Pending', null
    ),
    -- Prime minister badge
    (
     6, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"Vorname"},{"name":"surname","type":"String","value":"Nachname"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Straße"},{"name":"houseNumber","type":"String","value":"123"},{"name":"addressSupplement","type":"String","value":"Addreszusatz"},{"name":"postalCode","type":"String","value":"12345"},{"name":"location","type":"String","value":"Oberhopfenhausen"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"1999-12-12"},{"name":"telephone","type":"String","value":"12345"},{"name":"emailAddress","type":"String","value":"some@email.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Goldene Ehrenamtskarte"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"goldenCardHonoredByMinisterPresidentEntitlement","type":"Array","value":[{"name":"certificate","type":"Attachment","value":{"fileIndex":0}}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":true},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-05-20 16:39:51.228', 'access_key_06', NULL, NULL,'Pending', null
    ),
    -- Admin rejected
    (
        7, 1,
        '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
        '2025-05-20 16:39:51.228', 'access_key_07', NULL, NULL,'Rejected', current_timestamp
    ),
    -- Admin approved
    (
        8, 1,
        '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
        '2025-05-20 16:39:51.228', 'access_key_08', NULL, NULL,'Approved', current_timestamp
    ),
    -- Card created
    (
     9, 1,
     '{"name":"application","type":"Array","value":[{"name":"personalData","type":"Array","value":[{"name":"forenames","type":"String","value":"GivenName_00"},{"name":"surname","type":"String","value":"Surname_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"StreetName_00"},{"name":"houseNumber","type":"String","value":" StreeNumber_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"dateOfBirth","type":"Date","value":"2008-01-01"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"emailAddress","type":"String","value":"email_00@domain.com"}]},{"name":"applicationDetails","type":"Array","value":[{"name":"cardType","type":"String","value":"Blaue Ehrenamtskarte"},{"name":"applicationType","type":"String","value":"Erstantrag"},{"name":"wantsDigitalCard","type":"Boolean","value":true},{"name":"wantsPhysicalCard","type":"Boolean","value":false},{"name":"blueCardWorkAtOrganizationsEntitlement","type":"Array","value":[{"name":"workAtOrganization","type":"Array","value":[{"name":"organization","type":"Array","value":[{"name":"name","type":"String","value":"Associaction_00"},{"name":"address","type":"Array","value":[{"name":"street","type":"String","value":"Street_00"},{"name":"houseNumber","type":"String","value":"Number_00"},{"name":"addressSupplement","type":"String","value":"AddressExtra_00"},{"name":"postalCode","type":"String","value":"01234"},{"name":"location","type":"String","value":"Municipality_00"},{"name":"country","type":"String","value":"Deutschland"}]},{"name":"category","type":"String","value":"social"},{"name":"organizationContact","type":"Array","value":[{"name":"name","type":"String","value":"Some_Name_00"},{"name":"telephone","type":"String","value":"0123/456789"},{"name":"email","type":"String","value":"name_00@domain.de"},{"name":"hasGivenPermission","type":"Boolean","value":true}]}]},{"name":"responsibility","type":"String","value":"VolunteerWork_00"},{"name":"amountOfWork","type":"Number","value":10.0},{"name":"workSinceDate","type":"Date","value":"2022-01-01"},{"name":"payment","type":"Boolean","value":true},{"name":"isAlreadyVerified","type":"Boolean","value":false}]}]},{"name":"hasAcceptedPrivacyPolicy","type":"Boolean","value":true},{"name":"hasAcceptedEmailUsage","type":"Boolean","value":false},{"name":"givenInformationIsCorrectAndComplete","type":"Boolean","value":true}]}]}',
     '2025-05-20 16:39:51.228', 'access_key_09', NULL, NULL,'ApprovedCardCreated', current_timestamp
    )
ON CONFLICT ("id") DO UPDATE SET
    "regionId" = EXCLUDED."regionId",
    "jsonValue" = EXCLUDED."jsonValue",
    "createdDate" = EXCLUDED."createdDate",
    "accessKey" = EXCLUDED."accessKey",
    "withdrawalDate" = EXCLUDED."withdrawalDate",
    "note" = EXCLUDED."note",
    "status" = EXCLUDED."status",
    "statusResolvedDate" = EXCLUDED."statusResolvedDate"
;
