docker:
  - image: rust:bookworm
working_directory: ~/martin
steps:
  - checkout:
      path: ~/project
  - run: apt update -y && apt install -y nodejs npm
  - install_app_toolbelt
  - run:
      name: "Clone martin"
      command: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts
        git config --global advice.detachedHead false
        git clone --depth 1 --branch v0.13.0 git@github.com:maplibre/martin.git ~/martin
  - restore_cache:
      keys:
        - v1-cargo-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
  - prepare_workspace
  - run:
      name: "Build"
      command: |
        cargo build --release --target x86_64-unknown-linux-gnu
  - save_cache:
      paths:
        - "~/.cargo"
        - "target"
      key: v1-cargo-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
  - run:
      name: "Prepare storing"
      command: |
        mkdir -p ~/attached_workspace/artifacts/martin
        cp target/x86_64-unknown-linux-gnu/release/martin ~/attached_workspace/artifacts/martin
  - store_artifacts:
      path: ~/attached_workspace/artifacts
  - persist_to_workspace:
      root: ~/attached_workspace/artifacts
      paths:
        - martin/martin
  - notify