docker:
  - image: cimg/base:2026.04
resource_class: small
parameters:
  release:
    description: Whether this is a release build. If true, the source context is uploaded to Sentry.
    type: boolean
    default: false
environment:
  _JAVA_OPTIONS: "-Xmx3g"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
  RELEASE_BUILD: << parameters.release >>
working_directory: ~/project/backend
steps:
  - prepare_workspace
  - install_mise
  - run:
      name: Setup submodules
      command: |
        git submodule sync
        git submodule update --init
  - restore_cache:
      keys:
        - v1-gradle-{{ checksum "build.gradle.kts" }}
  - run:
      name: Build backend
      # Use `assemble` instead of `build` to not run tests
      command: mise x -- ./gradlew distTar
  - save_cache:
      key: v1-gradle-{{ checksum "build.gradle.kts" }}
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
  - persist_to_workspace:
      root: ~/project
      paths:
        - backend/build/distributions/*
  - notify
