docker:
  - image: cimg/base:2026.04
resource_class: medium
working_directory: ~/project/administration
steps:
  - prepare_workspace
  - install_mise
  - install_node_modules
  - run:
      name: Build
      command: mise x -- npm run build
  - persist_to_workspace:
      root: ~/project
      paths:
        - administration/build
  - notify
