docker:
  - image: cimg/base:2026.04
resource_class: small
working_directory: ~/project/administration
steps:
  - prepare_workspace
  - install_mise
  - check_circleci_config
  - install_node_modules
  - run:
      name: Typescript
      command: mise x -- npm run ts:check
  - run:
      name: Lint
      command: mise x -- npm run lint
  - run:
      name: Check circular dependencies
      command: mise x -- npm run check-circular-deps
  - run:
      name: Run tests and generate coverage report
      command: mise x -- npm run test:coverage -- --maxWorkers=1
  - store_artifacts:
      path: src/coverage
      destination: ~/attached_workspace/coverage
  - notify
