docker:
  - image: cimg/node:20.18.0
resource_class: small
working_directory: ~/project/administration
steps:
  - prepare_workspace
  - check_circleci_config
  - install_protobuf_linux
  - install_node_modules
  - run:
      name: Typescript
      command: npm run ts:check
  - run:
      name: Lint
      command: npm run lint
  - run:
      name: Check circular dependencies
      command: npm run check-circular-deps
  - run:
      name: Run tests and generate coverage report
      command: npm run test:coverage -- --maxWorkers=2
  - store_artifacts:
      path: src/coverage
      destination: ~/attached_workspace/coverage
  - notify
