docker:
  - image: cimg/base:2026.04
resource_class: small
working_directory: ~/project/frontend
steps:
  - prepare_workspace
  - install_mise
  - check_circleci_config
  - install_app_toolbelt
  - install_flutter_packages
  - run:
      name: Check formatting
      command: mise x -- dart format -l 120 -o none --set-exit-if-changed .
  - run:
      name: Setup build config
      # Statically use "bayern" build config for analyzing
      command: mise x -- flutter pub run build_runner build --define "df_build_config=name=bayern"
  - run:
      name: Analyze and lint
      command: |
        mise x -- flutter analyze --fatal-infos --fatal-warnings
        mise x -- flutter analyze pubs/df_build_config --fatal-infos --fatal-warnings
  - run:
      name: Test
      # flutter packages - run in vm to allow dart:mirrors - see: https://github.com/flutter/flutter/issues/29868#issuecomment-475982139
      command: |
        mise x -- flutter test --no-pub --reporter=expanded
        mise x -- flutter packages test pubs/df_build_config
  - notify
