docker:
  - image: cimg/base:2026.04
resource_class: small
environment:
  _JAVA_OPTIONS: "-Xmx3g"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
working_directory: ~/project/backend
steps:
  - prepare_workspace
  - install_mise
  - check_circleci_config
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: Setup submodules
      command: |
        git submodule sync
        git submodule update --init
  - restore_cache:
      keys:
        - v1-gradle-{{ checksum "build.gradle.kts" }}
  - run:
      name: Check GraphQL scheme stability
      command: |
        mise x java -- ./gradlew run --args="graphql-export ../specs/backend-api.graphql"
        git diff --exit-code ../specs/backend-api.graphql
  - run:
      name: Check backend formatting
      command: mise x java -- ./gradlew ktlintCheck
  - run:
      name: Test
      command: mise x java -- ./gradlew test
  - store_test_results:
      path: ./build/test-results
  - run:
      name: Generate test coverage report
      command: mise x java -- ./gradlew koverLog koverHtmlReport
  - store_artifacts:
      path: ./build/reports/kover/html
      destination: test-coverage-report
  - save_cache:
      key: v1-gradle-{{ checksum "build.gradle.kts" }}
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
  - notify
