# Deliver the app to the Google Play Store.
docker:
  - image: cimg/android:2026.03.1
resource_class: small
parameters:
  build_config:
    type: enum
    enum: [ bayern, nuernberg, koblenz ]
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
working_directory: ~/project/frontend/android
steps:
  - prepare_workspace
  - install_mise
  - install_app_toolbelt
  - run:
      name: '[FL] Play Store Upload'
      command: mise x -- fastlane android upload_to_playstore build_config_name:<< parameters.build_config >> production_delivery:"<< parameters.production_delivery >>" version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
  - notify
