docker:
  # https://playwright.dev/docs/ci#circleci
  - image: mcr.microsoft.com/playwright:v1.60.0-noble
  - image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: ehrenamtskarte
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
resource_class: medium
environment:
  _JAVA_OPTIONS: "-Xmx1g"
working_directory: ~/project
steps:
  - prepare_workspace
  - run:
      name: Setup submodules
      command: |
        git submodule sync
        git submodule update --init
  - install_mise
  - install_node_modules
  - run:
      name: Extract backend distribution
      command: tar -xf ~/attached_workspace/backend/build/distributions/backend.tar -C ~/
  - run:
      name: Migrate database
      # Run from backend directory, so mise can pick up the java toolchain
      working_directory: ~/project/backend
      command: mise x -- ~/backend/bin/backend migrate
  - run:
      name: Start backend
      environment:
        KOBLENZ_PEPPER: 123456789ABC
        JWT_SECRET: HelloWorld
      # Run from backend directory, so mise can pick up the java toolchain
      working_directory: ~/project/backend
      command: mise x -- ~/backend/bin/backend --disable-mail-service=true execute
      background: true
  - run:
      name: Install Playwright browsers
      working_directory: ~/project/administration
      command: mise x -- npm exec -- playwright install --with-deps chromium
      environment:
        DEBIAN_FRONTEND: noninteractive
        NEEDRESTART_MODE: a
  - run:
      name: Start administration frontend
      working_directory: ~/project/administration
      command: mise x -- npm run start:ci
      background: true
      environment:
        BROWSER: none
  - run:
      name: Check backend health
      command: curl --retry 120 --retry-delay 1 --retry-all-errors http://localhost:8000/health
  - run:
      name: Import dev data
      working_directory: ~/project/backend
      command: mise x -- ~/backend/bin/backend db-import-dev src/dev/sql
  - run:
      name: Run e2e tests
      working_directory: ~/project/administration
      # TODO Use sharding: https://playwright.dev/docs/ci#sharding-in-circleci
      command: mise x -- npm run test:e2e
  - store_artifacts:
      path: ~/project/administration/playwright-report
      destination: playwright-report
  - notify
