docker:
  - image: cimg/node:20.18.0
parameters:
  production:
    description: Whether builds are delivered to production or beta.
    type: boolean
steps:
  - when:
      condition: << parameters.production >>
      steps:
        - run:
            name: Install packages via webhook
            command: |
              curl https://webhook.entitlementcard.tuerantuer.org/hooks/install-backend-admin-$EAK_WEBHOOK
  - unless:
      condition: << parameters.production >>
      steps:
        - run:
            name: Install packages via webhook
            command: |
              curl https://webhook.entitlementcard-test.tuerantuer.org/hooks/install-backend-admin-$EAK_WEBHOOK
  - notify
