docker:
  - image: cimg/python:3.11
resource_class: small
environment:
  LLM_REVIEW_PR_NUMBER: << pipeline.parameters.llm_review_pr_number >>
steps:
  - checkout
  - run:
      name: Install python dependencies
      command: pip install --user "PyJWT[crypto]" requests
  - run:
      name: Request Deliverino installation access token
      command: |
        TOKEN=$(./.circleci/scripts/get_access_token.py)
        echo "export DELIVERINO_ACCESS_TOKEN=$TOKEN" >> $BASH_ENV
  - run:
      name: Run LLM PR review
      command: ./.circleci/scripts/llm-pr-review.py
  - notify
