# Promotes the app from Testflight to the Apple App Store.
parameters:
  build_config_name:
    type: enum
    enum: [bayern, nuernberg, koblenz]
    default: bayern
macos:
  xcode: 15.2.0
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
shell: /bin/bash --login -o pipefail
steps:
  - checkout
  - install_app_toolbelt
  - restore_ruby_cache:
      directory: ~/project/frontend/ios
  - run:
      name: '[FL] Appstore Connect Store Promotion'
      command: bundle exec fastlane ios appstoreconnect_promote build_config_name:<< parameters.build_config_name >>
      working_directory: frontend/ios
  - notify
