# Promotes the app from Testflight to the Apple App Store.
parameters:
  build_config:
    type: enum
    enum: [bayern, nuernberg, koblenz]
    default: bayern
macos:
  xcode: 16.4.0
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
working_directory: ~/project/frontend/ios
steps:
  - prepare_workspace
  - install_app_toolbelt
  - install_fastlane
  - run:
      name: '[FL] Appstore Connect Store Promotion'
      command: bundle exec fastlane ios appstoreconnect_promote build_config_name:<< parameters.build_config >>
  - notify
