# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do 
  desc "Generate new localized screenshots"
  lane :snap_bayern do
   sh "fvm flutter pub run build_runner build --define df_build_config=name=bayern"
   bundle_identifier = "de.nrw.it.ehrensachebayern"
    capture_screenshots(
      workspace: "Runner.xcworkspace", 
      scheme: "Bayern",
      app_identifier: bundle_identifier,
      output_directory: "./fastlane/screenshots/bayern",
      launch_arguments: [bundle_identifier]
    )
  end

  lane :snap_nuernberg do
    sh "fvm flutter pub run build_runner build --define df_build_config=name=nuernberg"
    bundle_identifier = "app.sozialpass.nuernberg"
    capture_screenshots(
      workspace: "Runner.xcworkspace", 
      scheme: "Nuernberg", 
      app_identifier: bundle_identifier,
      output_directory: "./fastlane/screenshots/nuernberg",
      launch_arguments: [bundle_identifier]
    )
  end
end
