export const dataPrivacyBaseText =
  'Diese Datenschutzerklärung bezieht sich auf die Verarbeitung personenbezogener Daten im Rahmen der digitalen bayerischen Ehrenamtskarte einschließlich verbundener Dienste.\n\n' +
  'Die digitale bayerische Ehrenamtskarte wird im Auftrag des Bayerischen Staatsministeriums für Familie, Arbeit und Soziales, Winzererstraße 9, 80797 München durch die Tür an Tür – Digitalfabrik gGmbH, Wertachstr. 29, 86153 Augsburg betrieben.\n\n' +
  'Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. \n\n' +
  'Der gesamte Programmcode der digitalen bayerischen Ehrenamtskarte ist darüber hinaus quelloffen lizenziert unter der MIT-Lizenz und kann hier eingesehen werden:\n https://github.com/digitalfabrik/entitlementcard\n\n' +
  'Für nähere Informationen zur Verarbeitung Ihrer personenbezogenen Daten können Sie uns unter den unten genannten Kontaktdaten erreichen.\n\n' +
  'Name und Kontaktdaten des Verantwortlichen im Sinne des §7 TMG\nChristian K. J. Diener\nLeiter Referat Öffentlichkeitsarbeit\nTelefon: 089 1261-1640\nTelefax: 089 1261-181640\nE-Mail: Oeffentlichkeitsarbeit@stmas.bayern.de \n\n' +
  'Kontaktdaten der Datenschutzbeauftragten\nTür an Tür – Digitalfabrik gGmbH\nHerr Daniel Kehne\nWertachstr. 29\n86153 Augsburg\n\n' +
  'E-Mail: digitalfabrik@tuerantuer.de\nTelefon: 0821 20990556\n\n' +
  'Allgemeines zum Thema Datenschutz finden Sie auf der Website des Bayerischen Landesbeauftragten für den Datenschutz (https://www.datenschutz-bayern.de). \n\n' +
  'Haftung im Sinne §§ 7 - 10 TMG\n' +
  'Das Bayerische Staatsministerium für Arbeit und Soziales, Familie und Integration stellt sein App-Angebot unter folgenden Nutzungsbedingungen zur Verfügung:\n\n' +
  'Die App "Ehrenamtskarte" ist nach § 7 Abs. 1 TMG für die eigenen Inhalte, die es zur Nutzung bereithält, nach den allgemeinen Vorschriften verantwortlich. Die Haftung für Schäden materieller oder ideeller Art, die durch die Nutzung der Inhalte verursacht wurden, ist ausgeschlossen, sofern nicht Vorsatz oder grobe Fahrlässigkeit vorliegt.\n\n' +
  'Bei der Zusammenstellung und Abgabe der Informationen von Vergünstigungen wird alle Sorgfalt walten gelassen. Eine Gewähr für die inhaltliche Vollständigkeit und Richtigkeit der Daten kann dennoch nicht übernommen werden. Insbesondere wird jede Haftung für solche Schäden ausgeschlossen, die bei Anwendern direkt oder indirekt daraus entstehen, dass die Daten genutzt werden.\n\n' +
  'Soweit ein Text von dritter Seite erstellt ist, wird die jeweilige Verfasserin oder der jeweilige Verfasser oder die verantwortliche Einrichtung namentlich benannt. In diesen Fällen ist die Verfasserin oder der Verfasser bzw. die genannte Einrichtung des jeweiligen Dokuments für den Inhalt verantwortlich.\n\n' +
  'Die App "Ehrenamtskarte" bewertet den Inhalt der verzeichneten Web-Sites zum Zeitpunkt ihrer Aufnahme in das Verzeichnis sorgfältig, und es werden nur solche Verweise aufgenommen, deren Inhalt nach Prüfung zum Zeitpunkt der Aufnahme nicht gegen geltendes Recht verstößt.\n\n' +
  'Die App "Ehrenamtskarte" macht sich den Inhalt der zugänglich gemachten fremden Websites jedoch ausdrücklich nicht zu Eigen. Die Inhalte der Sites, auf die verwiesen wird, können sich ständig ändern - das macht gerade das Wesen eines digitalen Angebots aus. Aus diesem Grund übernimmt die App "Ehrenamtskarte" trotz Prüfung keine Gewähr für die Korrektheit, Vollständigkeit und Verfügbarkeit der jeweiligen fremden Website.\n\n' +
  'Die App "Ehrenamtskarte" hat keinen Einfluss auf die aktuelle und zukünftige Gestaltung und Inhalte der Seiten. Die App "Ehrenamtskarte" übernimmt keine Haftung für Schäden, die aus der Benutzung der Links entstehen könnten.\n' +
  'Zwecke und Rechtsgrundlagen für die Verarbeitung personenbezogener DatenZweck der Verarbeitung ist die Erfüllung einer freiwilligen Aufgabe. Soweit Sie in eine Verarbeitung eingewilligt haben, stützt sich die Datenverarbeitung auf Art. 6 Abs. 1 Buchstabe a DSGVO.\n\n' +
  'Automatische Speicherung von DatenBei jedem Zugriff auf das Antragsformular (URL zum Antragsformular einfügen) oder die Nutzung der bayerischen Ehrenamtskarten-App (Android/iOS) werden folgende Nutzungsdaten gemäß § 15 Abs. 1 TMG bei jedem Aufruf mit aktiver Internetverbindung anonymisiert erhoben:\n' +
  '- Datum und Uhrzeit des Abrufs\n' +
  '- Name des aufgerufenen Internetdienstes, der aufgerufenen Ressource und der verwendeten Aktion\n' +
  '- Abfrage, die der Client gestellt hat\n' +
  '- übertragene Datenmenge\n' +
  '- Meldung, ob der Abruf erfolgreich war\n' +
  '- Browser-Identifikation (enthält in der Regel die Browserversion, sowie das Betriebssystem)\n' +
  '- Innerhalb der App eingegebene Suchen nach Adressen oder Vergünstigungen;\n' +
  '- Standort-Positionen, falls der Standort in den Apps freigegeben ist.\n\n' +
  'Sonstige Daten werden bei Ihrer Nutzung nicht automatisch erhoben und nicht an unsere Server gesendet. Nach dem Grundsatz der Datenvermeidung und der Datensparsamkeit, sowie dem Grundsatz der anonymen und pseudonymen Nutzung, wird nur das Minimum an Nutzungsdaten erhoben, soweit dies für den technischen Betrieb der Apps sowie die Ermittlung der aufgerufenen Inhalte erforderlich ist. Die erhobenen Informationen können weder direkt noch mit Hilfe von Zusatzwissen auf eine bestimmte Person zurückgeführt werden. Die einzelnen Nutzer können somit nicht identifiziert werden. Wir erstellen keine Nutzungsprofile.\n\n' +
  'Weitergabe erhobener Daten\nDaten, die beim Zugriff auf unsere Dienste erhoben worden sind, werden an Dritte außerhalb unserer Organisation nur übermittelt, soweit wir gesetzlich oder durch richterliche bzw. staatsanwaltschaftliche Anordnung dazu verpflichtet sind oder die Weitergabe im Falle von Angriffen auf die Internetinfrastruktur unserer Organisation zur Rechts- oder Strafverfolgung erforderlich ist. Es erfolgt keine Weitergabe zu kommerziellen Zwecken. \n\n' +
  'Eine Übermittlung der Daten in andere Staaten erfolgt nicht. Der Serverstandort ist Deutschland.\n\n' +
  'Zustimmung (Einwilligung) zur Erhebung, Nutzung und Verarbeitung personenbezogener Daten\nAußerhalb gesetzlicher Verpflichtungen dürfen personenbezogene Daten nur mit (und im Rahmen) Ihrer Zustimmung erhoben, genutzt oder verarbeitet werden. Um dies zu gewährleisten, müssen Sie z.B. bei der Beantragung der digitalen bayerischen Ehrenamtskarte explizit der Verarbeitung und Weitergabe Ihrer Daten zustimmen. Sollten Sie die digitale bayerischen Ehrenamtskarte über das Online-Formular auf (URL zum Antragsformular einfügen) beantragen wird die Tür an Tür – Digitalfabrik gGmbH die im Antragsformular angegebenen Daten erheben, verarbeiten und nutzen. Dies erfolgt ausschließlich für den Zweck der Ausstellung der Bayerischen Ehrenamtskarte, sowie der damit verbundenen Gewährung von Vergünstigungen und zugehörigen Kommunikationsmaßnahmen. Ihre Daten werden an das Bayerischen Staatsministerium für Familie, Arbeit und Soziales sowie die ausstellende Stadt- bzw. Kreisverwaltung an Ihrem im Antrag angegebenen Wohnsitz weitergegeben, um die Ehrenamtskarte sachgemäß auszustellen. Sofern der Prozess dies erfordert können Ihre Daten zum Zwecke des Erstellens der Ehrenamtskarte auch an einen externen Druckpartner weitergegeben werden sowie zur Verwaltung Ihrer Daten an die Lachnit & Rademacher GmbH, die die Online-Datenbank freinet-online betreiben und in der von den bayerischen Stadt- und Kreisverwaltungen auch Ehrenamtskarten-Inhaber:innen und Akzeptanzstellen gepflegt werden.\n\n' +
  'Alle Einwilligungen können verweigert bzw. jederzeit ohne Angabe von Gründen durch Mitteilung an digitalfabrik@tuerantuer.de widerrufen werden. In diesem Fall werden alle gespeicherten personenbezogenen Daten gelöscht und die Ehrenamtskarte verliert ihre Gültigkeit. Aus der Nicht-Einwilligung oder einem Widerruf darf Ihnen kein Nachteil entstehen. Ein Widerruf kann nur mit Wirkung für die Zukunft erklärt werden. \n\n' +
  'Einwilligung durch Minderjährige\nPersonen unter 18 Jahren sollten ohne Zustimmung der Erziehungsberechtigten keine personenbezogenen Daten an uns übermitteln. Gemäß Art. 8 DSGVO dürfen Kinder bis 16 Jahre solche Einwilligungen nur mit Zustimmung der Erziehungsberechtigten erklären. Personenbezogene Daten von Minderjährigen werden nicht bewusst erhoben und verarbeitet.\n\n' +
  'Datensicherheit\nWir verwenden technische und organisatorische Maßnahmen um Ihre Daten vor dem Zugriff Unberechtigter und vor Manipulation, Übermittlung, Verlust oder Zerstörung zu schützen. Unsere Sicherheitsverfahren überprüfen wir regelmäßig und passen sie dem technologischen Fortschritt an.\n\n' +
  'Offenlegung und Weitergabe personenbezogener Daten\nAlle personenbezogenen Daten werden ausschließlich mit Ihrer ausdrücklichen Zustimmung weitergegeben und werden für keine anderen Zwecke als die in unserer Datenschutzerklärung genannten, verwendet.\n\n' +
  'Datenerhebung, Datennutzung und Verarbeitung\nElektronische Datenerhebung innerhalb des WebangebotesWenn Sie innerhalb unserer Online-Dienste aufgefordert werden Daten über sich einzugeben, erfolgt deren Transport über das Internet unter Verwendung von SSL-Verschlüsselung, um Ihre Daten vor einer Kenntnisnahme durch Unbefugte zu schützen.\n\n' +
  'Elektronische Post (E-Mail)\nWir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. Wenn Sie uns E-Mails senden, wird Ihre E-Mail-Adresse nur für die Korrespondenz mit Ihnen verwendet. Informationen, die Sie unverschlüsselt per E-Mail an uns senden können, möglicherweise auf dem Übertragungsweg von Dritten gelesen werden. \n'

export const dataPrivacyBaseHeadline =
  'Datenschutzerklärung für die Nutzung und Beantragung der digitalen bayerischen Ehrenamtskarte'
