package app.ehrenamtskarte.backend.db.migration.migrations

import app.ehrenamtskarte.backend.db.migration.Migration
import app.ehrenamtskarte.backend.db.migration.Statement

@Suppress("ClassName")
internal class V0031_AddAcceptingStoreDescriptionsTable : Migration() {
    override val migrate: Statement = {
        exec(
            """
            CREATE TABLE acceptingstoredescriptions (
                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "storeId" integer NOT NULL,
                "description" character varying(2500) NULL,
                "language" character varying(2) NOT NULL DEFAULT 'DE',
                CONSTRAINT acceptingstoredescriptions_language_check CHECK (language IN ('EN', 'DE'))
            );
            CREATE INDEX "acceptingstoredescriptions_storeid_idx" ON "acceptingstoredescriptions" USING "btree" ("storeId");
            ALTER TABLE acceptingstoredescriptions 
            ADD CONSTRAINT fk_acceptingstoredescriptions_storeid__id FOREIGN KEY ("storeId") 
            REFERENCES acceptingstores(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
            
            INSERT INTO acceptingstoredescriptions ("storeId", "description", "language")
            SELECT id, description, 'DE'
            FROM acceptingstores
            WHERE description IS NOT NULL;
            
            ALTER TABLE acceptingstores DROP COLUMN "description";
            """.trimIndent(),
        )
    }
}
