# See
# https://www.slf4j.org/apidocs/org/slf4j/simple/SimpleLogger.html
# https://javalin.io/tutorials/javalin-logging

org.slf4j.simpleLogger.defaultLogLevel=INFO
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=YYYY-MM-dd HH:mm:ss.SSS
org.slf4j.simpleLogger.log.org.eclipse.jetty=INFO
# Silence the default 'exposedLogger'
org.slf4j.simpleLogger.log.Exposed=off
