name: 'PR'

on:
  pull_request:
    branches:
      - main
    paths:
      - .prettierrc
      - eslint.config-base.mjs
      - graphql.config.yml
      - package.json
      - package-lock.json
      - administration/**
      - build-configs/**

jobs:
  administration-check:
    name: 'administration check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: jdx/mise-action@v4.0.1
        with:
          version: v2026.5.12
          cache: false
          install: false
          experimental: true

      - name: Cache npm packages
        uses: ./.github/actions/cache-npm

      - name: Install node modules
        run: mise exec -- npm ci

      - name: Check Typescript
        run: mise exec -- npm run ts:check
        working-directory: administration

      - name: Run Lint
        run: mise exec -- npm run lint
        working-directory: administration

      - name: Check circular dependencies
        run: mise exec -- npm run check-circular-deps
        working-directory: administration

      - name: Run tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        with:
          base-coverage-file: report.json
          skip-step: install
          working-directory: administration
          test-script: mise exec -- npm run test:coverage -- --silent --ci --json --testLocationInResults --outputFile=report.json --maxWorkers=1

      - name: Run tests
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: mise exec -- npm run test -- --maxWorkers=1
        working-directory: administration

  build-configs-check:
    name: 'build-configs check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: jdx/mise-action@v4.0.1
        with:
          version: v2026.5.12
          cache: false
          install: false
          experimental: true

      - name: Cache npm packages
        uses: ./.github/actions/cache-npm

      - name: Install node modules
        run: mise exec -- npm ci

      - name: Run Lint
        run: mise exec -- npm run lint
        working-directory: build-configs
